const Users =[
 {
    username: 'jdoe',
    owner: 'John Doe',
    transaction: [{amount:200,
                   description: 'SCU ATM #001 check deposit'},
                  {amount:450,
                  description: 'e-transfer-deposit @john stewart'} , 
                  {amount: -400,
                  description:'stern\'s eatry'}, 
                  {amount: 3000,
                  description: 'paycheck - Glen\'s construction'}, 
                  {amount:-650,
                  description:'Auto loan - Hyundai'}, 
                  {amount: -130,
                  description:'family foods - Dakota'},
                   {amount:70,
                  description:'refund @family foods - Dakota'},
                   {amount:1300,
                  description: 'annual interest @mutual funds'}],
    interestRate: 1.2, // %
    pass: 1111,
  },
  
   {
    username:'jdavis',
    owner: 'Jessica Davis',
    transaction: [{amount:5000,
                   description: 'pay check @ govt MB'},
                  {amount:3400,
                  description: 'IG investment'}, 
                  {amount:-150,
                   description: 'Dakota family foods'}, 
                   {amount:-790,
                  description: ' rent'},
                   {amount:-3210,
                  description: 'loan payment'}, 
                  {amount:-1000,
                  description: 'IKEA furniture'},
                   {amount:8500,
                  description: 'Visions Electronics'},
                  {amount: -30,
                  description: 'MCDonalds Pembina'}],
    interestRate: 1.5,
    pass: 2222,
  },
  
  {
    username: 'swilliams',
    owner: 'Steven Thomas Williams',
    transaction: [{amount:200,
                    description: 'e-transfer deposit debby'},
                    {amount: -200,
                    description: 'Locker footwear'},
                    {amount: 340,
                    description: 'refund @Locker Footwear'},
                    {amount:-300,
                    description: 'Adidas Store'},
                    {amount: -20,
                    description: 'Wendy\'s'}, 
                    {amount:50,
                    description: 'e-tranfer deposit @ Kelley'},
                    {amount:400,
                    description: 'Redcross Support'},
                    {amount:-460,
                    description: 'Grocery Bazaar'}],
    interestRate: 0.7,
    pass: 3333,
  },
  
  {
    username: 'ssmith',
    owner: 'Sarah Smith',
    transaction: [
      {amount:430,
      description: 'paycheck @ Telus'},
      {amount: 1000,
      description: 'paycheck @SCU'},
      {amount:700,
      description: 'IG investment'},
      {amount:50,
      description: 'e-tranfer deposit David'},
      {amount:90,
      description:'refund Molly\'s Food Court'}],
    interestRate: 1,
    pass: 4444,
  }
]

//   const accounts = [account1, account2, account3, account4];

export default Users;